name: Build

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: windows/wooting-rgb-sdk.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            target: x64
          - os: windows-latest
            target: x86

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Add MSBuild to PATH (Windows)
        if: startsWith(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.1

      - name: Install dependencies
        uses: ConorMacBride/install-package@v1
        with:
          brew: hidapi
          apt: libhidapi-dev libhidapi-hidraw0

      - name: Build (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: cd linux && make

      - name: Build (Mac)
        if: startsWith(matrix.os, 'mac')
        run: cd mac && make

      # - name: Restore NuGet packages
      #   working-directory: ${{env.GITHUB_WORKSPACE}}
      #   run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build (Windows)
        if: startsWith(matrix.os, 'windows')
        working-directory: ${{env.GITHUB_WORKSPACE}}
        # Add additional options to the MSBuild command line here (like platform or verbosity level).
        # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{matrix.target}} ${{env.SOLUTION_FILE_PATH}}
